services:
  sqlserver:
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MYs0m3Str4ngePWD@
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P MYs0m3Str4ngePWD@ -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - secrets:/var/opt/mssql/secretssimplewebtosqllogger
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet-app
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YourDatabaseName;User Id=sa;Password=MYs0m3Str4ngePWD@;
    ports:
      - "80:8080"
    links:
      - sqlserver
    restart: always
volumes:
  data:
  secrets:
